### PR TITLE
init:k8s

### PR DESCRIPTION
**Pull request by Dzerdevwarnd**
test pull request

### CODE REVIEW

**Comment by inctagramback** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by inctagramback** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Pull request closed without merging**
