### PR TITLE
jenkins 

### PR DESCRIPTION
**Pull request by Dzerdevwarnd**

### CODE REVIEW

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by Dzerdevwarnd** [comment]
run build production auth-microservice

**Comment by ivansukhoparov** [comment]
run build production auth-microservice

**Pull request merged**
